CREATE DATABASE burgers_db;
USE burgers_db;

DROP TABLE IF EXISTS burgers;
CREATE TABLE burgers (id INT AUTO_INCREMENT NOT NULL, burger_name VARCHAR(255) NOT NULL, devoured BOOL NOT NULL DEFAULT 0, PRIMARY KEY (id));